// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMMT-x8QwrF49RCdv7z0OXiZI9hBAYQ-8',
    appId: '1:550353514684:web:00534a3bb430b7bc6320b9',
    messagingSenderId: '550353514684',
    projectId: 'barbu-barbearia',
    authDomain: 'barbu-barbearia.firebaseapp.com',
    storageBucket: 'barbu-barbearia.firebasestorage.app',
    measurementId: 'G-VP780PYL8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlJ5Ib0ReTTrKhoykWXObYxe8Iuu3eI4',
    appId: '1:550353514684:android:b8d5debab4d9d0746320b9',
    messagingSenderId: '550353514684',
    projectId: 'barbu-barbearia',
    storageBucket: 'barbu-barbearia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlIXE-Y582yo71CsGJLhEruPQot_ez9w',
    appId: '1:550353514684:ios:ae242338b8d150606320b9',
    messagingSenderId: '550353514684',
    projectId: 'barbu-barbearia',
    storageBucket: 'barbu-barbearia.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlIXE-Y582yo71CsGJLhEruPQot_ez9w',
    appId: '1:550353514684:ios:ae242338b8d150606320b9',
    messagingSenderId: '550353514684',
    projectId: 'barbu-barbearia',
    storageBucket: 'barbu-barbearia.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMMT-x8QwrF49RCdv7z0OXiZI9hBAYQ-8',
    appId: '1:550353514684:web:acfdb6aceee35f546320b9',
    messagingSenderId: '550353514684',
    projectId: 'barbu-barbearia',
    authDomain: 'barbu-barbearia.firebaseapp.com',
    storageBucket: 'barbu-barbearia.firebasestorage.app',
    measurementId: 'G-3JLHRRQBJX',
  );
}
